apiserver:
  replicaCount: 2

  service:
    type: LoadBalancer
    port: 443
    loadBalancerIP: 172.18.202.101
    clusterIP: 10.254.0.99

controllerManager:
  replicaCount: 1

scheduler:
  replicaCount: 1

etcdCluster:
  size: 1
  annotations:
    etcd.database.coreos.com/scope: clusterwide
