apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: arp
      arp-network: 172.18.0.0/16
      cidr:
      - 172.18.202.0/24
